### PR TITLE
Handle comments that appear inside of structs, enums and services

### LINKED ISSUE #7: Doesn't parse comments
Just tried to parse:
```thrift
struct MyStruct {
    1: required i32 id,
    2: required bool field1,
    # 3: required string field,
    4: required i16 field,
}
```
And it failed.  I removed the commented line and it succeeds.

### PR DESCRIPTION
**Pull request by kevinbgreene**
Fixed #7 

Previously comments that appeared inside of a struct, enum or service would error:

This was fine:
```
// comment here
struct MyStruct {
  1: required i32 field1;
}
```

This wasn't:
```
struct MyStruct {
  // 1: required i32 field1;
}
```

### CODE REVIEW

**Comment by kevinbgreene** [comment]
@phated Reopened this so I could clean it up a bit and not screw up my history.

File: src/parser.ts [hunk 1]
```diff
@@ -747,15 +762,15 @@ export function createParser(tkns: Array<Token>): Parser {
   // MapType → 'map' CppType? '<' FieldType ',' FieldType '>'
   function parseMapType(): MapType {
     const openBracket: Token = consume(SyntaxType.LessThanToken);
-    requireValue(openBracket, `map needs to defined contained types`);
+    requireValue(openBracket, `Map needs to defined contained types`);
 
     const keyType: FieldType = parseFieldType();
     const commaToken: Token = consume(SyntaxType.CommaToken);
-    requireValue(commaToken, `comma expedted to separate map types <key, value>`);
+    requireValue(commaToken, `Comma expedted to separate map types <key, value>`);
```
Comment (phated) [inline src/parser.ts]: Nitpick: expedted -> expected

File: src/parser.ts [hunk 2]
```diff
@@ -188,15 +188,17 @@ export function createParser(tkns: Array<Token>): Parser {
...
+        functions.push(parseFunction());
 
-      if (check(SyntaxType.RightBraceToken)) {
-        break;
-      } else if (isStatementBeginning(currentToken())) {
-        throw new ParseError(`Closing curly brace expected, but new statement found`);
-      } else if (check(SyntaxType.EOF)) {
-        throw new ParseError(`Closing curly brace expected but reached end of file`);
+        if (isStatementBeginning(currentToken())) {
+          throw new ParseError(`closing curly brace expected, but new statement found`);
```
Comment (phated) [inline src/parser.ts]: Nitpick: Capitalize like the other errors

File: src/parser.ts [hunk 3]
```diff
@@ -188,15 +188,17 @@ export function createParser(tkns: Array<Token>): Parser {
...
+        } else if (check(SyntaxType.EOF)) {
+          throw new ParseError(`closing curly brace expected but reached end of file`);
```
Comment (phated) [inline src/parser.ts]: Nitpick: Capitalize like the other errors

**Review by phated — CHANGES_REQUESTED** [review]
@kevinbgreene It looks like you lost the tests for comments in structs and services during the rebase.

I also found that
```thrift
service Service1 {
    int test() /* */ throws (1: MyError err; 2: string test)
}
```
doesn't parse but maybe that should be another issue?

**Comment by kevinbgreene** [comment]
@phated Yeah, I've been thinking about the cleanest way to handle something like:

```
service Service1 {
    int test() /* */ throws (1: MyError err; 2: string test)
}
```

It would be easy to pull out all comments during scanning and just ignore them. I want to leave them in the AST to provide the option for them to be in the codegen. I've got something in mind I'll put in another PR if that works.

**Comment by phated** [comment]
Sounds good. I'll open a tracking issue and approve here.

**Review by phated — APPROVED** [review]

**Comment by phated** [comment]
@kevinbgreene oops, I forgot that the tests were still missing.  Can you add them back in? Maybe in that other PR?
